#!/bin/sh
# Tiny POSIX compliant fetch script
# Requires nerdfont to display icons

# customise what to display here
main() {
    # call all functions
    for func in title distro wm kernel shell memory uptime disk colors; do
        $func
    done

    # display information
    printf "%b\n" "               $title
  $(c 34 '⠀⠀⠀⠀⠀⠀⢀⣴⣾⠆')   $(c 35 )  $os ${wmname:+- $wmname}
  $(c 34 '⢶⣶⡶⡴⢦⣼⣟⣻⣿⠀')   $(c 35 )  $kernel
  $(c 34 '⠀⠙⣿⡳⣋⡿⣦⡲⣺')    $(c 35 )  $shell
  $(c 34 '⠀⠀⠸⣼⣸⠟⠀⠛⠃')    $(c 35 󰏖)  $disk
               $(c 35 󰏘)  $palette"
}

# colorsise input
c() {
    printf "\033[%sm%s\033[0m" "$1" "$2"  # see above for usage
}

title() {
    title="${USER:-$(id -un)}@$(hostname)"
}

distro() {
    # distribution name
    [ -f /etc/os-release ] && . /etc/os-release
    os="$(printf "%s" "${PRETTY_NAME:-Linux}" | tr '[:upper:]' '[:lower:]')"

    # package count (add yours if not present)
    case "$os" in
        *void*) pkg="$(xbps-query -l | wc -l) (xbps)" ;;
        *kiss*) pkg="$(ls /var/db/kiss/installed | wc -l) (kiss)" ;;
        *alpine*|*chimera*) pkg="$(apk list --installed | wc -l) (apk)" ;;
        *) pkg="0 (unknown)" ;;
    esac
}

wm() {
    wmname=$(printf "%s" "${XDG_CURRENT_DESKTOP:-unknown}" | 
        tr '[:upper:]' '[:lower:]')
}

kernel () {
    read -r _ _ kernel _ < /proc/version
}

shell() {
    shell=${SHELL##*/}
}

uptime() {
    u=$(cut -d' ' -f1 /proc/uptime); u=${u%.*}
    d=$(( u/86400)); h=$((u/3600%24)); m=$((u/60%60))
    [ "$d" -ge 1 ] && uptime="${d}d "
    [ "$h" -ge 1 ] && uptime="${uptime}${h}h "
    uptime="${uptime}${m}m"
}

memory() {
    u=0; t=0
    while IFS=: read -r a b; do
        b=${b% kB}
        case $a in
            MemTotal) t=$b; u=$b ;;
            Shmem) u=$((u + b)) ;;
            MemFree|Buffers|Cached|SReclaimable) u=$((u - b)) ;;
        esac
    done </proc/meminfo
    u=$((u / 1024)); t=$((t / 1024))
    memory="${u}MiB / ${t}MiB"
}

disk() {
    disk=$(df -k "${disk_show:-/}" | awk 'NR==2{
        used=$3/1048576
        total=$2/1048576
        perc=int($3*100/$2)
        printf "%.2f GiB / %.2f GiB (%d%%)", used, total, perc
    }')
}

colors() {
    i=0
    while [ "$i" -lt 8 ]; do
        palette="${palette}\033[48;5;${i}m   \033[0m"
        i=$((i+1))
    done
}

# fetch away!
main
